name: Check Docker Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker secrets
        run: |
          echo "Checking secrets..."
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME is NOT set"
            exit 1
          fi
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "DOCKER_PASSWORD is NOT set"
            exit 1
          fi
          echo "All secrets are set ✅"
