name: Test Docker Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify Docker Secrets
        run: |
          echo "DOCKER_USERNAME is set"
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME is NOT set"
            exit 1
          fi
          echo "DOCKER_PASSWORD is set"
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "DOCKER_PASSWORD is NOT set"
            exit 1
          fi
